@extends('Admin.Layout.master')
@section('title', 'Data BMD - Kelurahan XXXXX')
@section('page_title', 'Data BMD')
@section('page_subtitle', 'Kesekretariatan · Data BMD')
@push('styles')
<style>
.content-header,.table-panel-header{display:flex;align-items:center;justify-content:space-between;gap:18px}.content-header{margin-bottom:25px}.content-header h2{font:26px Georgia,serif;color:#18364d}.content-header p,.table-panel-header p{font-size:12px;color:var(--muted);margin-top:6px}.btn-add{display:inline-flex;gap:8px;align-items:center;background:var(--primary);color:#fff;border:0;border-radius:7px;padding:11px 16px;font-size:12px;font-weight:bold}.table-panel{background:#fff;border:1px solid var(--border);border-radius:10px;overflow:hidden}.table-panel-header{padding:20px 22px;border-bottom:1px solid var(--border)}.table-panel-header h3{font-size:16px;color:#18364d}.total-data{color:var(--primary);background:var(--primary-light);border-radius:20px;padding:6px 10px;font-size:11px}.table-wrapper{padding:0 22px 20px;overflow-x:auto}#bmdTable{width:100%!important;margin-top:15px!important}#bmdTable th{background:#f8faf9;color:#52616b;font-size:11px;padding:13px 12px;white-space:nowrap}#bmdTable td{padding:14px 12px;font-size:12px;border-bottom:1px solid #f0f2f3}.action-buttons{display:flex;gap:6px}.action-btn{width:31px;height:31px;border:1px solid var(--border);border-radius:6px;background:#fff;cursor:pointer}.action-view{color:#2d6a9f}.action-edit{color:var(--primary)}.action-delete{color:#c0392b}@media(max-width:700px){.content-header{align-items:flex-start;flex-direction:column}}
</style>
@endpush
@section('content')
<div class="content-header"><div><h2>Data BMD</h2><p>Kelola data barang milik daerah Kelurahan XXXXX.</p></div><a href="{{ url('/tambah-data-bmd') }}" class="btn-add">+ Tambah Data</a></div>
<section class="table-panel"><div class="table-panel-header"><div><h3>Daftar Barang</h3><p>Data BMD Kelurahan XXXXX</p></div><span class="total-data" id="totalData">5 Barang</span></div><div class="table-wrapper"><table id="bmdTable" class="display"><thead><tr><th>Nama Barang</th><th>Tipe</th><th>Tahun Perolehan</th><th>Sumber Dana</th><th>Kondisi</th><th>Keterangan</th><th>Aksi</th></tr></thead><tbody>
<tr><td>Laptop Lenovo ThinkPad</td><td>Elektronik</td><td>2023</td><td>APBD</td><td>Baik</td><td>Untuk administrasi kelurahan</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit" onclick="editData()">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
<tr><td>Meja kerja kayu</td><td>Perabot</td><td>2022</td><td>APBD</td><td>Baik</td><td>Ruang pelayanan umum</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit" onclick="editData()">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
<tr><td>Printer Epson L3210</td><td>Elektronik</td><td>2024</td><td>DAK</td><td>Baik</td><td>Cetak dokumen dan laporan</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit" onclick="editData()">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
<tr><td>Kursi tunggu besi</td><td>Perabot</td><td>2021</td><td>APBD</td><td>Cukup Baik</td><td>Area tunggu masyarakat</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit" onclick="editData()">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
<tr><td>Toyota Avanza</td><td>Kendaraan</td><td>2020</td><td>APBD</td><td>Baik</td><td>Operasional kelurahan</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit" onclick="editData()">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
</tbody></table></div></section>
@endsection
@push('scripts')
<script src="https://cdn.datatables.net/2.1.8/js/dataTables.min.js"></script><script>const bmdTable=new DataTable('#bmdTable',{pageLength:10,columnDefs:[{orderable:false,searchable:false,targets:6}]});bmdTable.on('draw',()=>document.getElementById('totalData').textContent=bmdTable.page.info().recordsDisplay+' Barang');function viewData(button){const c=button.closest('tr').cells;alert('Detail Data BMD\n\nNama Barang: '+c[0].innerText+'\nTipe: '+c[1].innerText+'\nTahun: '+c[2].innerText+'\nSumber Dana: '+c[3].innerText+'\nKondisi: '+c[4].innerText+'\nKeterangan: '+c[5].innerText)}function editData(){window.location.href='{{ url('/edit-data-bmd') }}'}function hapusData(button){if(confirm('Hapus data barang ini?'))button.closest('tr').remove()}</script>
@endpush
