@php
    $isEdit = $isEdit ?? false;
    $bmdValue = fn (string $key, mixed $default = '') => old($key, data_get($bmd ?? null, $key, $default));
@endphp
@extends('Admin.Layout.master')
@section('title', ($isEdit ? 'Edit' : 'Tambah') . ' Data BMD - Kelurahan XXXXX')
@section('page_title', ($isEdit ? 'Edit' : 'Tambah') . ' Data BMD')
@section('page_subtitle', 'Kesekretariatan · Data BMD · ' . ($isEdit ? 'Edit Data' : 'Tambah Data'))
@push('styles')
<style>
.breadcrumb{display:flex;gap:8px;color:var(--muted);font-size:12px;margin-bottom:18px}.breadcrumb a{color:var(--primary)}.page-title-block{margin-bottom:25px}.page-title-block h2{font:27px Georgia,serif;color:#18364d;margin-bottom:7px}.page-title-block p{font-size:13px;color:var(--muted)}.form-card{background:#fff;border:1px solid var(--border);border-radius:10px;overflow:hidden}.form-header,.form-footer{background:#fbfcfc;padding:22px 25px;border-bottom:1px solid var(--border)}.form-header h3{font-size:17px;color:#18364d;margin-bottom:5px}.form-header p,.form-help,.required-note{font-size:12px;color:var(--muted)}.form-body{padding:28px 25px}.form-section{margin-bottom:30px}.section-title{display:flex;gap:10px;align-items:center;color:#18364d;font-size:14px;font-weight:bold;padding-bottom:12px;margin-bottom:20px;border-bottom:1px solid var(--border)}.section-number{width:25px;height:25px;border-radius:50%;background:var(--primary-light);color:var(--primary);display:flex;align-items:center;justify-content:center}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px 25px}.form-group{display:flex;flex-direction:column}.form-group.full{grid-column:1/-1}.form-group label{font-size:12px;font-weight:bold;margin-bottom:8px}.required{color:#c0392b}.form-control{width:100%;height:43px;border:1px solid #dce2e5;border-radius:7px;padding:0 13px;font:13px Arial,sans-serif;color:var(--text);background:#fff}.form-control:focus{border-color:var(--primary);outline:0;box-shadow:0 0 0 3px rgba(8,116,67,.08)}textarea.form-control{height:100px;padding:12px;resize:vertical}.info-box{display:flex;gap:12px;padding:14px 16px;background:var(--primary-light);border:1px solid #d7ecdf;border-radius:8px}.info-icon{width:24px;height:24px;border-radius:50%;background:var(--primary);color:#fff;display:flex;align-items:center;justify-content:center;flex-shrink:0}.info-box p{font-size:12px;line-height:1.6;color:#416052}.form-footer{display:flex;justify-content:space-between;align-items:center;border-top:1px solid var(--border);border-bottom:0}.form-actions{display:flex;gap:10px}.btn{height:42px;padding:0 20px;border-radius:7px;display:inline-flex;align-items:center;justify-content:center;font-size:12px;font-weight:bold;border:0;cursor:pointer}.btn-secondary{background:#fff;color:var(--text);border:1px solid #dce2e5}.btn-primary{background:var(--primary);color:#fff}@media(max-width:700px){.form-grid{grid-template-columns:1fr}.form-group.full{grid-column:auto}.form-footer{flex-direction:column;align-items:stretch;gap:15px}.form-actions .btn{flex:1}}
</style>
@endpush
@section('content')
<div class="breadcrumb"><a href="{{ url('/dashboard') }}">Beranda</a><span>›</span><a href="{{ url('/databmd') }}">Data BMD</a><span>›</span><span>{{ $isEdit ? 'Edit Data' : 'Tambah Data' }}</span></div>
<div class="page-title-block"><h2>{{ $isEdit ? 'Edit Data BMD' : 'Tambah Data BMD' }}</h2><p>{{ $isEdit ? 'Perbarui informasi barang milik daerah Kelurahan XXXXX.' : 'Tambahkan data barang milik daerah Kelurahan XXXXX.' }}</p></div>
<div class="form-card"><div class="form-header"><h3>{{ $isEdit ? 'Edit Data BMD' : 'Form Data BMD' }}</h3><p>Lengkapi informasi barang pada kolom yang tersedia.</p></div>
<form id="bmdForm" method="POST" action="{{ url()->current() }}">@csrf @if($isEdit) @method('PUT') @endif<div class="form-body">
<div class="form-section"><div class="section-title"><span class="section-number">1</span>Identitas Barang</div><div class="form-grid"><div class="form-group"><label for="nama_barang">Nama Barang <span class="required">*</span></label><input type="text" id="nama_barang" name="nama_barang" class="form-control" placeholder="Contoh: Laptop Lenovo ThinkPad" value="{{ $bmdValue('nama_barang') }}" required></div><div class="form-group"><label for="tipe">Tipe <span class="required">*</span></label><select id="tipe" name="tipe" class="form-control" required><option value="">Pilih Tipe</option>@foreach(['Elektronik','Perabot','Kendaraan','Lainnya'] as $tipe)<option value="{{ $tipe }}" @selected($bmdValue('tipe') === $tipe)>{{ $tipe }}</option>@endforeach</select></div><div class="form-group full"><label for="tahun_perolehan">Tahun Perolehan <span class="required">*</span></label><input type="number" id="tahun_perolehan" name="tahun_perolehan" class="form-control" min="1900" max="2100" placeholder="Contoh: 2024" value="{{ $bmdValue('tahun_perolehan') }}" required></div></div></div>
<div class="form-section"><div class="section-title"><span class="section-number">2</span>Detail Barang</div><div class="form-grid"><div class="form-group"><label for="sumber_dana">Sumber Dana <span class="required">*</span></label><select id="sumber_dana" name="sumber_dana" class="form-control" required><option value="">Pilih Sumber Dana</option>@foreach(['APBD','DAK','Hibah','Lainnya'] as $sumber)<option value="{{ $sumber }}" @selected($bmdValue('sumber_dana') === $sumber)>{{ $sumber }}</option>@endforeach</select></div><div class="form-group"><label for="kondisi">Kondisi <span class="required">*</span></label><select id="kondisi" name="kondisi" class="form-control" required><option value="">Pilih Kondisi</option>@foreach(['Baik','Cukup Baik','Rusak Ringan','Rusak Berat'] as $kondisi)<option value="{{ $kondisi }}" @selected($bmdValue('kondisi') === $kondisi)>{{ $kondisi }}</option>@endforeach</select></div><div class="form-group full"><label for="keterangan">Keterangan</label><textarea id="keterangan" name="keterangan" class="form-control" placeholder="Keterangan barang">{{ $bmdValue('keterangan') }}</textarea></div></div></div>
<div class="info-box"><div class="info-icon">i</div><p>{{ $isEdit ? 'Periksa kembali perubahan data barang sebelum menyimpan.' : 'Pastikan data barang yang dimasukkan sudah benar sebelum menyimpan.' }}</p></div></div><div class="form-footer"><div class="required-note"><span class="required">*</span> Wajib diisi</div><div class="form-actions"><a href="{{ url('/databmd') }}" class="btn btn-secondary">Batal</a><button type="submit" class="btn btn-primary">{{ $isEdit ? 'Perbarui Data' : 'Simpan Data' }}</button></div></div></form></div>
@endsection
@push('scripts')
@if(!$isEdit)<script>document.getElementById('bmdForm')?.addEventListener('submit',function(e){e.preventDefault();alert('Data BMD berhasil disimpan!\n\nNama Barang: '+document.getElementById('nama_barang').value);window.location.href='{{ url('/databmd') }}'});</script>@endif
@endpush
