<?php

namespace Database\Seeders;

use App\Models\DataUmkm;
use Illuminate\Database\Seeder;

class DataUmkmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DataUmkm::create([
            'nama_pelaku_usaha' => 'Siti Aminah',
            'nik' => '3273014501850001',
            'no_kk' => '3273014501850002',
            'no_telepon' => '081234567890',
            'nama_usaha' => 'Warung Makan Berkah',
            'jenis_usaha' => 'Kuliner',
            'alamat_usaha' => 'Jl. Melati No. 12, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567890',
            'npwp' => '123456789012345',
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Makanan dan Minuman',
            'modal_usaha' => 15000000,
            'omzet_bulanan' => 8500000,
            'jumlah_tenaga_kerja' => 3,
            'skala_usaha' => 'Mikro',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Usaha kuliner rumahan.',
            'google_sync_status' => 'pending',
        ]);

        DataUmkm::create([
            'nama_pelaku_usaha' => 'Budi Santoso',
            'nik' => '3273011202780003',
            'no_kk' => '3273011202780004',
            'no_telepon' => '081323456781',
            'nama_usaha' => 'Toko Sumber Rezeki',
            'jenis_usaha' => 'Perdagangan',
            'alamat_usaha' => 'Jl. Mawar No. 25, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567891',
            'npwp' => '123456789012346',
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Sembako dan Kebutuhan Rumah Tangga',
            'modal_usaha' => 35000000,
            'omzet_bulanan' => 18000000,
            'jumlah_tenaga_kerja' => 4,
            'skala_usaha' => 'Kecil',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Toko kebutuhan sehari-hari masyarakat.',
            'google_sync_status' => 'pending',
        ]);

        DataUmkm::create([
            'nama_pelaku_usaha' => 'Andi Wijaya',
            'nik' => '3273012303900005',
            'no_kk' => '3273012303900006',
            'no_telepon' => '082145678901',
            'nama_usaha' => 'Bengkel Maju Motor',
            'jenis_usaha' => 'Jasa',
            'alamat_usaha' => 'Jl. Kenanga No. 8, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567892',
            'npwp' => '123456789012347',
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Servis Sepeda Motor',
            'modal_usaha' => 45000000,
            'omzet_bulanan' => 22000000,
            'jumlah_tenaga_kerja' => 5,
            'skala_usaha' => 'Kecil',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Bengkel sepeda motor dan penjualan suku cadang.',
            'google_sync_status' => 'pending',
        ]);

        DataUmkm::create([
            'nama_pelaku_usaha' => 'Rina Lestari',
            'nik' => '3273015604920007',
            'no_kk' => '3273015604920008',
            'no_telepon' => '085712345678',
            'nama_usaha' => 'Butik Cantik Fashion',
            'jenis_usaha' => 'Fashion',
            'alamat_usaha' => 'Jl. Anggrek No. 17, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567893',
            'npwp' => '123456789012348',
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Pakaian Wanita',
            'modal_usaha' => 28000000,
            'omzet_bulanan' => 14500000,
            'jumlah_tenaga_kerja' => 3,
            'skala_usaha' => 'Kecil',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Produksi dan penjualan pakaian wanita.',
            'google_sync_status' => 'pending',
        ]);

        DataUmkm::create([
            'nama_pelaku_usaha' => 'Dedi Haryanto',
            'nik' => '3273011001750009',
            'no_kk' => '3273011001750010',
            'no_telepon' => '081987654321',
            'nama_usaha' => 'Tani Makmur',
            'jenis_usaha' => 'Pertanian',
            'alamat_usaha' => 'Jl. Flamboyan No. 5, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567894',
            'npwp' => '123456789012349',
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Sayuran dan Tanaman Pangan',
            'modal_usaha' => 20000000,
            'omzet_bulanan' => 12000000,
            'jumlah_tenaga_kerja' => 4,
            'skala_usaha' => 'Mikro',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Usaha pertanian dan pemasaran hasil panen.',
            'google_sync_status' => 'pending',
        ]);

        DataUmkm::create([
            'nama_pelaku_usaha' => 'Nurhayati',
            'nik' => '3273016502830011',
            'no_kk' => '3273016502830012',
            'no_telepon' => '082234567890',
            'nama_usaha' => 'Kue Bu Nuri',
            'jenis_usaha' => 'Kuliner',
            'alamat_usaha' => 'Jl. Dahlia No. 21, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567895',
            'npwp' => null,
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Kue Tradisional dan Snack',
            'modal_usaha' => 10000000,
            'omzet_bulanan' => 6500000,
            'jumlah_tenaga_kerja' => 2,
            'skala_usaha' => 'Mikro',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Produksi kue rumahan berdasarkan pesanan.',
            'google_sync_status' => 'pending',
        ]);

        DataUmkm::create([
            'nama_pelaku_usaha' => 'Agus Setiawan',
            'nik' => '3273011505860013',
            'no_kk' => '3273011505860014',
            'no_telepon' => '081345678902',
            'nama_usaha' => 'Percetakan Binong Jaya',
            'jenis_usaha' => 'Jasa',
            'alamat_usaha' => 'Jl. Cempaka No. 14, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567896',
            'npwp' => '123456789012350',
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Percetakan dan Fotokopi',
            'modal_usaha' => 40000000,
            'omzet_bulanan' => 20000000,
            'jumlah_tenaga_kerja' => 4,
            'skala_usaha' => 'Kecil',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Jasa percetakan, fotokopi, dan desain grafis.',
            'google_sync_status' => 'pending',
        ]);

        DataUmkm::create([
            'nama_pelaku_usaha' => 'Yuni Kartika',
            'nik' => '3273015707940015',
            'no_kk' => '3273015707940016',
            'no_telepon' => '085612345679',
            'nama_usaha' => 'Yuni Craft',
            'jenis_usaha' => 'Kerajinan',
            'alamat_usaha' => 'Jl. Teratai No. 9, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567897',
            'npwp' => null,
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Kerajinan Dekorasi Rumah',
            'modal_usaha' => 12000000,
            'omzet_bulanan' => 7500000,
            'jumlah_tenaga_kerja' => 2,
            'skala_usaha' => 'Mikro',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Produksi kerajinan dekorasi rumah.',
            'google_sync_status' => 'pending',
        ]);

        DataUmkm::create([
            'nama_pelaku_usaha' => 'Fajar Ramadhan',
            'nik' => '3273011801980017',
            'no_kk' => '3273011801980018',
            'no_telepon' => '083812345680',
            'nama_usaha' => 'Fajar Elektronik',
            'jenis_usaha' => 'Perdagangan',
            'alamat_usaha' => 'Jl. Kamboja No. 30, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567898',
            'npwp' => '123456789012351',
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Elektronik dan Aksesori',
            'modal_usaha' => 50000000,
            'omzet_bulanan' => 28000000,
            'jumlah_tenaga_kerja' => 5,
            'skala_usaha' => 'Kecil',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Penjualan perangkat elektronik dan aksesori.',
            'google_sync_status' => 'pending',
        ]);

        DataUmkm::create([
            'nama_pelaku_usaha' => 'Euis Komalasari',
            'nik' => '3273014203870019',
            'no_kk' => '3273014203870020',
            'no_telepon' => '081223456781',
            'nama_usaha' => 'Laundry Bersih Binong',
            'jenis_usaha' => 'Jasa',
            'alamat_usaha' => 'Jl. Mawar No. 41, Kelurahan Binong',
            'kelurahan' => 'Binong',
            'kecamatan' => 'Batununggal',
            'kabupaten_kota' => 'Kota Bandung',
            'nib' => '9120304567899',
            'npwp' => null,
            'izin_usaha' => 'NIB',
            'produk_utama' => 'Laundry Kiloan',
            'modal_usaha' => 18000000,
            'omzet_bulanan' => 9500000,
            'jumlah_tenaga_kerja' => 3,
            'skala_usaha' => 'Mikro',
            'status_usaha' => 'Aktif',
            'keterangan' => 'Jasa laundry pakaian dan perlengkapan rumah tangga.',
            'google_sync_status' => 'pending',
        ]);
    }
}
