@extends('Admin.Layout.master')
@section('title','Data Posyandu & Posbindu - Kelurahan XXXXX')
@section('page_title','Data Posyandu & Posbindu')
@section('page_subtitle','Kesejahteraan Sosial · Posyandu & Posbindu')
@push('styles')<style>.content-header,.table-panel-header{display:flex;align-items:center;justify-content:space-between;gap:18px}.content-header{margin-bottom:25px}.content-header h2{font:26px Georgia,serif;color:#18364d}.content-header p,.table-panel-header p{font-size:12px;color:var(--muted);margin-top:6px}.btn-add{display:inline-flex;background:var(--primary);color:#fff;border-radius:7px;padding:11px 16px;font-size:12px;font-weight:bold}.table-panel{background:#fff;border:1px solid var(--border);border-radius:10px;overflow:hidden}.table-panel-header{padding:20px 22px;border-bottom:1px solid var(--border)}.table-panel-header h3{font-size:16px;color:#18364d}.total-data{color:var(--primary);background:var(--primary-light);border-radius:20px;padding:6px 10px;font-size:11px}.table-wrapper{padding:0 22px 20px;overflow-x:auto}#posyanduTable{width:100%!important;margin-top:15px!important}#posyanduTable th{background:#f8faf9;color:#52616b;font-size:11px;padding:13px 12px;white-space:nowrap}#posyanduTable td{padding:14px 12px;font-size:12px;border-bottom:1px solid #f0f2f3}.action-buttons{display:flex;gap:6px}.action-btn{width:31px;height:31px;border:1px solid var(--border);border-radius:6px;background:#fff;cursor:pointer}.action-view{color:#2d6a9f}.action-edit{color:var(--primary)}.action-delete{color:#c0392b}@media(max-width:700px){.content-header{align-items:flex-start;flex-direction:column}}</style>@endpush
@section('content')
<div class="content-header"><div><h2>Data Posyandu & Posbindu</h2><p>Kelola data Posyandu dan Posbindu Kelurahan XXXXX.</p></div><a href="{{ url('/tambah-data-posyandu') }}" class="btn-add">+ Tambah Data</a></div>
<section class="table-panel"><div class="table-panel-header"><div><h3>Daftar Posyandu & Posbindu</h3><p>Data Posyandu & Posbindu Kelurahan XXXXX</p></div><span class="total-data" id="totalData">5 Data</span></div><div class="table-wrapper"><table id="posyanduTable" class="display"><thead><tr><th>Jenis</th><th>Nama</th><th>RW</th><th>Jumlah Kader</th><th>Keterangan</th><th>Aksi</th></tr></thead><tbody>
<tr><td>Posyandu</td><td>Posyandu Melati</td><td>05</td><td>8</td><td>Aktif melayani warga</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit" onclick="editData()">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
<tr><td>Posyandu</td><td>Posyandu Mawar</td><td>06</td><td>7</td><td>Aktif melayani warga</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
<tr><td>Posbindu</td><td>Posbindu Sehat</td><td>03</td><td>6</td><td>Aktif melayani warga lanjut usia</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
<tr><td>Posyandu</td><td>Posyandu Kenanga</td><td>02</td><td>9</td><td>Aktif melayani balita dan ibu</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
<tr><td>Posbindu</td><td>Posbindu Sehat Bersama</td><td>08</td><td>5</td><td>Aktif melayani warga</td><td><div class="action-buttons"><button class="action-btn action-view" onclick="viewData(this)">◉</button><button class="action-btn action-edit">✎</button><button class="action-btn action-delete" onclick="hapusData(this)">×</button></div></td></tr>
</tbody></table></div></section>
@endsection
@push('scripts')<script src="https://cdn.datatables.net/2.1.8/js/dataTables.min.js"></script><script>const posyanduTable=new DataTable('#posyanduTable',{pageLength:10,columnDefs:[{orderable:false,searchable:false,targets:5}]});posyanduTable.on('draw',()=>document.getElementById('totalData').textContent=posyanduTable.page.info().recordsDisplay+' Data');document.querySelectorAll('.action-edit').forEach(b=>b.addEventListener('click',()=>editData()));function editData(){window.location.href='{{url('/edit-data-posyandu')}}'}function viewData(b){const c=b.closest('tr').cells;alert('Detail Posyandu & Posbindu\n\nJenis: '+c[0].innerText+'\nNama: '+c[1].innerText+'\nRW: '+c[2].innerText+'\nJumlah Kader: '+c[3].innerText+'\nKeterangan: '+c[4].innerText)}function hapusData(b){if(confirm('Hapus data ini?'))b.closest('tr').remove()}</script>@endpush
